#!/bin/bash
CONFIGFILE="/usr/local/src/octoprint-usb-autoconnect/octoprint_usb_autoconnect.conf"

if [ ! -f ${CONFIGFILE} ]; then
    echo "Configuration file \"${CONFIGFILE}\""
    exit 1
fi

# Load config file
. ${CONFIGFILE}

# Send POST request to reconnect serial connection
curl -siL -X POST -H "Content-Type: application/json" -H "X-Api-Key: ${APIKEY}" ${OCTOHOST}/api/connection -d '{"command":"connect"}'
